### ISSUE TITLE
Is there a way to bust the local cache ?

### ISSUE THREAD

**Issue by MisterBrownRSA** [spatie/vue-save-state#13]
Sometimes I have to manually disable the entire... mixin/plugin to make the cached data go away. Is there a call for this ?

**Comment by rickbolton** [comment]
@MisterBrownRSA is this for development purposes as you can clear your local storage via Chrome dev tools - 
<img width="560" alt="screen shot 2018-03-16 at 11 43 44" src="https://user-images.githubusercontent.com/10371256/37518961-5c4c26c8-290f-11e8-98b1-5a52decfa05f.png">
Otherwise you could potentially remove it using something like https://github.com/localForage/localForage maybe?

**Comment by dsaket** [comment]
@MisterBrownRSA I was facing the same issue. The only solution that worked for me was to manually delete the LocalStorage key `window.localStorage.removeItem(cacheKeyName)`.
